# mlTrainer ML Configuration
# Machine Learning pipeline configuration with regime-aware model selection

models:
  RandomForest:
    enabled: true
    parameters:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42
      n_jobs: -1
    regime_suitability:
      stable: 0.8
      trending: 0.6
      volatile: 0.4
      crisis: 0.3
    training:
      batch_size: 1000
      incremental: false
      
  XGBoost:
    enabled: true
    parameters:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
      n_jobs: -1
    regime_suitability:
      stable: 0.7
      trending: 0.9
      volatile: 0.8
      crisis: 0.6
    training:
      batch_size: 2000
      incremental: false
      early_stopping_rounds: 10
      
  LightGBM:
    enabled: true
    parameters:
      n_estimators: 100
      learning_rate: 0.1
      num_leaves: 31
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
      verbosity: -1
    regime_suitability:
      stable: 0.7
      trending: 0.85
      volatile: 0.8
      crisis: 0.7
    training:
      batch_size: 2000
      incremental: false
      
  LSTM:
    enabled: false  # Requires TensorFlow
    parameters:
      units: 50
      dropout: 0.2
      recurrent_dropout: 0.2
      epochs: 50
      batch_size: 32
      sequence_length: 20
    regime_suitability:
      stable: 0.6
      trending: 0.8
      volatile: 0.9
      crisis: 0.8
    training:
      batch_size: 64
      incremental: true
      validation_split: 0.2
      
  Transformer:
    enabled: false  # Requires TensorFlow
    parameters:
      d_model: 64
      num_heads: 8
      num_layers: 4
      dropout: 0.1
      epochs: 30
      batch_size: 32
    regime_suitability:
      stable: 0.5
      trending: 0.7
      volatile: 0.9
      crisis: 0.9
    training:
      batch_size: 32
      incremental: true
      
  EnsembleVoting:
    enabled: true
    voting_strategy: "soft"
    base_models: ["RandomForest", "XGBoost", "LightGBM"]
    weights: "auto"  # or specific weights
    regime_suitability:
      stable: 0.9
      trending: 0.9
      volatile: 0.8
      crisis: 0.7

# Training configuration
training:
  test_size: 0.2
  validation_size: 0.1
  min_samples: 100
  max_samples: 50000
  retrain_threshold: 0.7  # Retrain if accuracy drops below this
  cross_validation:
    enabled: true
    folds: 5
    scoring: "accuracy"
  walk_forward:
    enabled: true
    window_size: 252  # Trading days (1 year)
    step_size: 21     # Trading days (1 month)
    min_train_size: 756  # 3 years
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
  class_balancing:
    method: "auto"  # auto, smote, random_undersample
    ratio: "auto"

# Feature engineering
features:
  technical_indicators:
    enabled: true
    indicators:
      - sma_5
      - sma_10
      - sma_20
      - sma_50
      - ema_12
      - ema_26
      - rsi_14
      - macd
      - bollinger_bands
      - atr_14
      - volume_sma_10
    lookback_periods: [5, 10, 20]
    
  price_features:
    enabled: true
    features:
      - returns
      - log_returns
      - volatility
      - price_momentum
      - high_low_ratio
      - open_close_ratio
    periods: [1, 5, 10, 20]
    
  volume_features:
    enabled: true
    features:
      - volume_ratio
      - volume_momentum
      - price_volume_trend
      - volume_weighted_price
    
  macro_features:
    enabled: true
    features:
      - vix_level
      - interest_rate_environment
      - yield_curve_slope
      - dollar_strength
    update_frequency: "daily"
    
  sentiment_features:
    enabled: true
    features:
      - reddit_sentiment
      - insider_activity
      - options_flow
      - news_sentiment
    update_frequency: "hourly"

# Model selection and regime awareness
regime_classification:
  volatility_thresholds:
    low: 20
    medium: 50
    high: 80
  macro_signal_weights:
    vix: 0.3
    interest_rates: 0.2
    unemployment: 0.2
    sentiment: 0.3
  regime_persistence:
    min_duration_hours: 24
    stability_threshold: 0.8

# Performance monitoring
monitoring:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - auc_roc
    - sharpe_ratio
    - max_drawdown
  tracking:
    by_regime: true
    by_model: true
    by_timeframe: true
  alerts:
    accuracy_drop_threshold: 0.1
    performance_degradation_days: 7
    
# Model persistence and versioning
persistence:
  save_models: true
  model_directory: "models/"
  versioning: true
  compression: true
  max_versions_per_model: 5
  auto_cleanup_days: 30
  
# Resource management
resources:
  max_memory_gb: 8
  max_cpu_cores: 4
  gpu_enabled: false
  parallel_training: true
  cache_features: true
  cache_size_gb: 2
  
# Compliance and validation
compliance:
  validate_training_data: true
  require_data_lineage: true
  audit_predictions: true
  model_explainability: true
  bias_detection: true
  fairness_metrics: true
  
# Experimentation
experiments:
  hyperparameter_tuning:
    enabled: true
    method: "random_search"  # grid_search, random_search, bayesian
    max_evals: 50
    cv_folds: 3
  feature_selection:
    enabled: true
    method: "recursive_elimination"
    max_features: 50
  model_comparison:
    enabled: true
    metrics: ["accuracy", "f1_score", "auc_roc"]
    statistical_tests: true
