"""
Company name mappings for ticker symbols.
Used for displaying tooltips with full company names.
"""

COMPANY_NAMES = {
    # Technology
    'AAPL': 'Apple Inc.',
    'MSFT': 'Microsoft Corporation',
    'GOOGL': 'Alphabet Inc. Class A',
    'GOOG': 'Alphabet Inc. Class C',
    'AMZN': 'Amazon.com Inc.',
    'TSLA': 'Tesla Inc.',
    'META': 'Meta Platforms Inc.',
    'NVDA': 'NVIDIA Corporation',
    'NFLX': 'Netflix Inc.',
    'ADBE': 'Adobe Inc.',
    'CRM': 'Salesforce Inc.',
    'ORCL': 'Oracle Corporation',
    'IBM': 'International Business Machines Corporation',
    'CSCO': 'Cisco Systems Inc.',
    'INTC': 'Intel Corporation',
    'AMD': 'Advanced Micro Devices Inc.',
    'QCOM': 'QUALCOMM Incorporated',
    'AVGO': 'Broadcom Inc.',
    'TXN': 'Texas Instruments Incorporated',
    'NOW': 'ServiceNow Inc.',
    'SHOP': 'Shopify Inc.',
    'SNOW': 'Snowflake Inc.',
    'DDOG': 'Datadog Inc.',
    'ZM': 'Zoom Video Communications Inc.',
    'DOCU': 'DocuSign Inc.',
    'OKTA': 'Okta Inc.',
    'CRWD': 'CrowdStrike Holdings Inc.',
    'PLTR': 'Palantir Technologies Inc.',
    'PINS': 'Pinterest Inc.',
    'SNAP': 'Snap Inc.',
    'TWTR': 'Twitter Inc.',
    'UBER': 'Uber Technologies Inc.',
    'LYFT': 'Lyft Inc.',
    'ABNB': 'Airbnb Inc.',
    'ROKU': 'Roku Inc.',
    'SQ': 'Block Inc.',
    'PYPL': 'PayPal Holdings Inc.',
    'ETSY': 'Etsy Inc.',
    'ZS': 'Zscaler Inc.',
    'NET': 'Cloudflare Inc.',
    'CYBR': 'CyberArk Software Ltd.',
    'CRSP': 'CRISPR Therapeutics AG',
    'TENB': 'Tenable Holdings Inc.',
    'U': 'Unity Software Inc.',
    
    # Healthcare & Biotech
    'JNJ': 'Johnson & Johnson',
    'PFE': 'Pfizer Inc.',
    'UNH': 'UnitedHealth Group Incorporated',
    'ABBV': 'AbbVie Inc.',
    'TMO': 'Thermo Fisher Scientific Inc.',
    'ABT': 'Abbott Laboratories',
    'BMY': 'Bristol-Myers Squibb Company',
    'LLY': 'Eli Lilly and Company',
    'MDT': 'Medtronic plc',
    'GILD': 'Gilead Sciences Inc.',
    'AMGN': 'Amgen Inc.',
    'CVS': 'CVS Health Corporation',
    'ISRG': 'Intuitive Surgical Inc.',
    'MRNA': 'Moderna Inc.',
    'REGN': 'Regeneron Pharmaceuticals Inc.',
    'BIIB': 'Biogen Inc.',
    'VRTX': 'Vertex Pharmaceuticals Incorporated',
    'IQV': 'IQVIA Holdings Inc.',
    'ZTS': 'Zoetis Inc.',
    'DHR': 'Danaher Corporation',
    'BSX': 'Boston Scientific Corporation',
    'SYK': 'Stryker Corporation',
    'EW': 'Edwards Lifesciences Corporation',
    'ALGN': 'Align Technology Inc.',
    'ILMN': 'Illumina Inc.',
    'TECH': 'Bio-Techne Corporation',
    'WAT': 'Waters Corporation',
    'PKI': 'PerkinElmer Inc.',
    'BDX': 'Becton Dickinson and Company',
    'BAX': 'Baxter International Inc.',
    
    # Financial Services
    'BRK.B': 'Berkshire Hathaway Inc. Class B',
    'JPM': 'JPMorgan Chase & Co.',
    'BAC': 'Bank of America Corporation',
    'WFC': 'Wells Fargo & Company',
    'GS': 'The Goldman Sachs Group Inc.',
    'MS': 'Morgan Stanley',
    'C': 'Citigroup Inc.',
    'AXP': 'American Express Company',
    'V': 'Visa Inc.',
    'MA': 'Mastercard Incorporated',
    'BLK': 'BlackRock Inc.',
    'SPGI': 'S&P Global Inc.',
    'MCO': 'Moody\'s Corporation',
    'ICE': 'Intercontinental Exchange Inc.',
    'CME': 'CME Group Inc.',
    'PGR': 'The Progressive Corporation',
    'TRV': 'The Travelers Companies Inc.',
    'ALL': 'The Allstate Corporation',
    'MET': 'MetLife Inc.',
    'PRU': 'Prudential Financial Inc.',
    'AIG': 'American International Group Inc.',
    'CB': 'Chubb Limited',
    'AON': 'Aon plc',
    'MMC': 'Marsh & McLennan Companies Inc.',
    'BK': 'The Bank of New York Mellon Corporation',
    'STT': 'State Street Corporation',
    'NTRS': 'Northern Trust Corporation',
    'SCHW': 'The Charles Schwab Corporation',
    'TROW': 'T. Rowe Price Group Inc.',
    'BEN': 'Franklin Resources Inc.',
    'IVZ': 'Invesco Ltd.',
    'KEY': 'KeyCorp',
    'RF': 'Regions Financial Corporation',
    'ZION': 'Zions Bancorporation N.A.',
    'HBAN': 'Huntington Bancshares Incorporated',
    'CFG': 'Citizens Financial Group Inc.',
    'FITB': 'Fifth Third Bancorp',
    'MTB': 'M&T Bank Corporation',
    'PNC': 'The PNC Financial Services Group Inc.',
    'USB': 'U.S. Bancorp',
    'TFC': 'Truist Financial Corporation',
    'LPL': 'LPL Financial Holdings Inc.',
    
    # Energy
    'XOM': 'Exxon Mobil Corporation',
    'CVX': 'Chevron Corporation',
    'COP': 'ConocoPhillips',
    'EOG': 'EOG Resources Inc.',
    'SLB': 'Schlumberger Limited',
    'PXD': 'Pioneer Natural Resources Company',
    'KMI': 'Kinder Morgan Inc.',
    'WMB': 'The Williams Companies Inc.',
    'OKE': 'ONEOK Inc.',
    'MPC': 'Marathon Petroleum Corporation',
    'VLO': 'Valero Energy Corporation',
    'PSX': 'Phillips 66',
    'HES': 'Hess Corporation',
    'DVN': 'Devon Energy Corporation',
    'FANG': 'Diamondback Energy Inc.',
    'MRO': 'Marathon Oil Corporation',
    'OVV': 'Ovintiv Inc.',
    'APA': 'APA Corporation',
    'HAL': 'Halliburton Company',
    'BKR': 'Baker Hughes Company',
    
    # Utilities
    'NEE': 'NextEra Energy Inc.',
    'DUK': 'Duke Energy Corporation',
    'SO': 'The Southern Company',
    'D': 'Dominion Energy Inc.',
    'EXC': 'Exelon Corporation',
    'XEL': 'Xcel Energy Inc.',
    'SRE': 'Sempra Energy',
    'AEP': 'American Electric Power Company Inc.',
    'PCG': 'PG&E Corporation',
    'ED': 'Consolidated Edison Inc.',
    'FE': 'FirstEnergy Corp.',
    'ETR': 'Entergy Corporation',
    'ES': 'Eversource Energy',
    'CMS': 'CMS Energy Corporation',
    'DTE': 'DTE Energy Company',
    'NI': 'NiSource Inc.',
    'LNT': 'Alliant Energy Corporation',
    'AES': 'The AES Corporation',
    'NRG': 'NRG Energy Inc.',
    'VST': 'Vistra Corp.',
    
    # Consumer Discretionary
    'HD': 'The Home Depot Inc.',
    'MCD': 'McDonald\'s Corporation',
    'SBUX': 'Starbucks Corporation',
    'NKE': 'NIKE Inc.',
    'LOW': 'Lowe\'s Companies Inc.',
    'TJX': 'The TJX Companies Inc.',
    'BKNG': 'Booking Holdings Inc.',
    'CMG': 'Chipotle Mexican Grill Inc.',
    'MAR': 'Marriott International Inc.',
    'HLT': 'Hilton Worldwide Holdings Inc.',
    'MGM': 'MGM Resorts International',
    'LVS': 'Las Vegas Sands Corp.',
    'WYNN': 'Wynn Resorts Limited',
    'CCL': 'Carnival Corporation & plc',
    'RCL': 'Royal Caribbean Cruises Ltd.',
    'NCLH': 'Norwegian Cruise Line Holdings Ltd.',
    'UAL': 'United Airlines Holdings Inc.',
    'DAL': 'Delta Air Lines Inc.',
    'AAL': 'American Airlines Group Inc.',
    'LUV': 'Southwest Airlines Co.',
    'ALK': 'Alaska Air Group Inc.',
    'JBLU': 'JetBlue Airways Corporation',
    'F': 'Ford Motor Company',
    'GM': 'General Motors Company',
    'RACE': 'Ferrari N.V.',
    'LCID': 'Lucid Group Inc.',
    'RIVN': 'Rivian Automotive Inc.',
    'NIO': 'NIO Inc.',
    'XPEV': 'XPeng Inc.',
    'LI': 'Li Auto Inc.',
    
    # Consumer Staples
    'PG': 'The Procter & Gamble Company',
    'KO': 'The Coca-Cola Company',
    'PEP': 'PepsiCo Inc.',
    'WMT': 'Walmart Inc.',
    'COST': 'Costco Wholesale Corporation',
    'CL': 'Colgate-Palmolive Company',
    'KMB': 'Kimberly-Clark Corporation',
    'GIS': 'General Mills Inc.',
    'K': 'Kellogg Company',
    'CPB': 'Campbell Soup Company',
    'SJM': 'The J. M. Smucker Company',
    'HSY': 'The Hershey Company',
    'MDLZ': 'Mondelez International Inc.',
    'KHC': 'The Kraft Heinz Company',
    'MNST': 'Monster Beverage Corporation',
    'KDP': 'Keurig Dr Pepper Inc.',
    'STZ': 'Constellation Brands Inc.',
    'TAP': 'Molson Coors Beverage Company',
    'BUD': 'Anheuser-Busch InBev SA/NV',
    'PM': 'Philip Morris International Inc.',
    'MO': 'Altria Group Inc.',
    'BTI': 'British American Tobacco p.l.c.',
    'ABEV': 'Ambev S.A.',
    
    # Industrials
    'BA': 'The Boeing Company',
    'GE': 'General Electric Company',
    'MMM': '3M Company',
    'HON': 'Honeywell International Inc.',
    'UPS': 'United Parcel Service Inc.',
    'CAT': 'Caterpillar Inc.',
    'DE': 'Deere & Company',
    'LMT': 'Lockheed Martin Corporation',
    'RTX': 'Raytheon Technologies Corporation',
    'NOC': 'Northrop Grumman Corporation',
    'GD': 'General Dynamics Corporation',
    'LHX': 'L3Harris Technologies Inc.',
    'TXT': 'Textron Inc.',
    'ITW': 'Illinois Tool Works Inc.',
    'EMR': 'Emerson Electric Co.',
    'ETN': 'Eaton Corporation plc',
    'PH': 'Parker-Hannifin Corporation',
    'ROK': 'Rockwell Automation Inc.',
    'DOV': 'Dover Corporation',
    'FTV': 'Fortive Corporation',
    'IR': 'Ingersoll Rand Inc.',
    'CARR': 'Carrier Global Corporation',
    'OTIS': 'Otis Worldwide Corporation',
    'JCI': 'Johnson Controls International plc',
    'TT': 'Trane Technologies plc',
    'SPX': 'SPX Technologies Inc.',
    'XYL': 'Xylem Inc.',
    'IEX': 'IDEX Corporation',
    'FLS': 'Flowserve Corporation',
    'PNR': 'Pentair plc',
    'A': 'Agilent Technologies Inc.',
    'TMO': 'Thermo Fisher Scientific Inc.',
    'DHR': 'Danaher Corporation',
    'LDOS': 'Leidos Holdings Inc.',
    'BAH': 'Booz Allen Hamilton Holding Corporation',
    'CACI': 'CACI International Inc Class A',
    'SAIC': 'Science Applications International Corporation',
    'KBR': 'KBR Inc.',
    'FTI': 'TechnipFMC plc',
    'SLG': 'SL Green Realty Corp.',
    'BXP': 'Boston Properties Inc.',
    'VTR': 'Ventas Inc.',
    'WELL': 'Welltower Inc.',
    'HCP': 'Healthpeak Properties Inc.',
    'MPW': 'Medical Properties Trust Inc.',
    'O': 'Realty Income Corporation',
    'STORE': 'STORE Capital Corporation',
    'NNN': 'NNN REIT Inc.',
    'WPC': 'W. P. Carey Inc.',
    'ADC': 'Agree Realty Corporation',
    'FRT': 'Federal Realty Investment Trust',
    'REG': 'Regency Centers Corporation',
    'KIM': 'Kimco Realty Corporation',
    'BRX': 'Brixmor Property Group Inc.',
    'SPG': 'Simon Property Group Inc.',
    'MAC': 'Macerich Company',
    'PEI': 'Pennsylvania Real Estate Investment Trust',
    'TCO': 'Taubman Centers Inc.',
    'SKT': 'Tanger Factory Outlet Centers Inc.',
    'PLD': 'Prologis Inc.',
    'EXR': 'Extended Stay America Inc.',
    'PSA': 'Public Storage',
    'CUBE': 'CubeSmart',
    'REXR': 'Rexford Industrial Realty Inc.',
    'FR': 'First Industrial Realty Trust Inc.',
    'EQIX': 'Equinix Inc.',
    'DLR': 'Digital Realty Trust Inc.',
    'COR': 'CoreSite Realty Corporation',
    'QTS': 'QTS Realty Trust Inc.',
    'CONE': 'CyrusOne Inc.',
    'SBRA': 'Sabra Health Care REIT Inc.',
    'HR': 'Healthcare Realty Trust Incorporated',
    'PEAK': 'Healthpeak Properties Inc.',
    'DOC': 'Physicians Realty Trust',
    'LTC': 'LTC Properties Inc.',
    'OHI': 'Omega Healthcare Investors Inc.',
    'HTA': 'Healthcare Trust of America Inc.',
    'MPW': 'Medical Properties Trust Inc.',
    'GMRE': 'Global Medical REIT Inc.',
    'CXW': 'CoreCivic Inc.',
    'GEO': 'The GEO Group Inc.',
    
    # Materials
    'LIN': 'Linde plc',
    'APD': 'Air Products and Chemicals Inc.',
    'ECL': 'Ecolab Inc.',
    'SHW': 'The Sherwin-Williams Company',
    'FCX': 'Freeport-McMoRan Inc.',
    'NEM': 'Newmont Corporation',
    'GOLD': 'Barrick Gold Corporation',
    'AEM': 'Agnico Eagle Mines Limited',
    'KGC': 'Kinross Gold Corporation',
    'AU': 'AngloGold Ashanti Limited',
    'HMY': 'Harmony Gold Mining Company Limited',
    'GFI': 'Gold Fields Limited',
    'PAAS': 'Pan American Silver Corp.',
    'HL': 'Hecla Mining Company',
    'AG': 'First Majestic Silver Corp.',
    'WPM': 'Wheaton Precious Metals Corp.',
    'FNV': 'Franco-Nevada Corporation',
    'RGLD': 'Royal Gold Inc.',
    'SAND': 'Sandstorm Gold Ltd.',
    'SSL': 'Sandstorm Gold Ltd.',
    'EGO': 'Eldorado Gold Corporation',
    'IAG': 'IAMGOLD Corporation',
    'NGD': 'New Gold Inc.',
    'CDE': 'Coeur Mining Inc.',
    'SBSW': 'Sibanye Stillwater Limited',
    'PLG': 'Platinum Group Metals Ltd.',
    'SVM': 'Silvercorp Metals Inc.',
    'SSRM': 'SSR Mining Inc.',
    'MUX': 'McEwen Mining Inc.',
    'GORO': 'Gold Resource Corporation',
    'Mgold': 'Barrick Gold Corporation',
    'NTR': 'Nutrien Ltd.',
    'CF': 'CF Industries Holdings Inc.',
    'MOS': 'The Mosaic Company',
    'FMC': 'FMC Corporation',
    'ALB': 'Albemarle Corporation',
    'SQM': 'Sociedad Química y Minera de Chile S.A.',
    'IFF': 'International Flavors & Fragrances Inc.',
    'FUL': 'H.B. Fuller Company',
    'RPM': 'RPM International Inc.',
    'PPG': 'PPG Industries Inc.',
    'AXP': 'American Express Company',
    'EMN': 'Eastman Chemical Company',
    'LYB': 'LyondellBasell Industries N.V.',
    'DOW': 'Dow Inc.',
    'DD': 'DuPont de Nemours Inc.',
    'CC': 'The Chemours Company',
    'WLK': 'Westlake Chemical Corporation',
    'OLN': 'Olin Corporation',
    'STLD': 'Steel Dynamics Inc.',
    'NUE': 'Nucor Corporation',
    'CMC': 'Commercial Metals Company',
    'RS': 'Reliance Steel and Aluminum Co.',
    'ATI': 'ATI Inc.',
    'CENX': 'Century Aluminum Company',
    'AA': 'Alcoa Corporation',
    'X': 'United States Steel Corporation',
    'CLF': 'Cleveland-Cliffs Inc.',
    'MT': 'ArcelorMittal S.A.',
    'PKG': 'Packaging Corporation of America',
    'WRK': 'WestRock Company',
    'IP': 'International Paper Company',
    'KMB': 'Kimberly-Clark Corporation',
    'AVY': 'Avery Dennison Corporation',
    'CCK': 'Crown Holdings Inc.',
    'BALL': 'Ball Corporation',
    'AMCR': 'Amcor plc',
    'SEE': 'Sealed Air Corporation',
    'SON': 'Sonoco Products Company',
    'GPK': 'Graphic Packaging Holding Company',
    'SLGN': 'Silgan Holdings Inc.',
    'BLL': 'Ball Corporation',
    'CCL': 'Carnival Corporation & plc',
    'O-I': 'O-I Glass Inc.',
    'CLW': 'Clearwater Paper Corporation',
    'UFPI': 'UFP Industries Inc.',
    'BCC': 'Boise Cascade Company',
    'WY': 'Weyerhaeuser Company',
    'PCH': 'PotlatchDeltic Corporation',
    'RYN': 'Rayonier Inc.',
    'CUT': 'Acadian Timber Corp.',
    
    # Communication Services
    'GOOGL': 'Alphabet Inc. Class A',
    'GOOG': 'Alphabet Inc. Class C',
    'META': 'Meta Platforms Inc.',
    'NFLX': 'Netflix Inc.',
    'DIS': 'The Walt Disney Company',
    'VZ': 'Verizon Communications Inc.',
    'T': 'AT&T Inc.',
    'TMUS': 'T-Mobile US Inc.',
    'CMCSA': 'Comcast Corporation',
    'CHTR': 'Charter Communications Inc.',
    'DISH': 'DISH Network Corporation',
    'SIRI': 'Sirius XM Holdings Inc.',
    'FOXA': 'Fox Corporation Class A',
    'FOX': 'Fox Corporation Class B',
    'PARA': 'Paramount Global Class B',
    'WBD': 'Warner Bros. Discovery Inc.',
    'NWSA': 'News Corporation Class A',
    'NWS': 'News Corporation Class B',
    'NYT': 'The New York Times Company',
    'IPG': 'The Interpublic Group of Companies Inc.',
    'OMC': 'Omnicom Group Inc.',
    'WPP': 'WPP plc',
    'PINS': 'Pinterest Inc.',
    'SNAP': 'Snap Inc.',
    'TWTR': 'Twitter Inc.',
    'SPOT': 'Spotify Technology S.A.',
    'ROKU': 'Roku Inc.',
    'RBLX': 'Roblox Corporation',
    'U': 'Unity Software Inc.',
    'ZM': 'Zoom Video Communications Inc.',
    'DOCU': 'DocuSign Inc.',
    'TEAM': 'Atlassian Corporation',
    'WDAY': 'Workday Inc.',
    'VEEV': 'Veeva Systems Inc.',
    'ZS': 'Zscaler Inc.',
    'NET': 'Cloudflare Inc.',
    'CRWD': 'CrowdStrike Holdings Inc.',
    'OKTA': 'Okta Inc.',
    'DDOG': 'Datadog Inc.',
    'MDB': 'MongoDB Inc.',
    'SNOW': 'Snowflake Inc.',
    'PLTR': 'Palantir Technologies Inc.',
    'SPLK': 'Splunk Inc.',
    'PANW': 'Palo Alto Networks Inc.',
    'CYBR': 'CyberArk Software Ltd.',
    'FTNT': 'Fortinet Inc.',
    'CHKP': 'Check Point Software Technologies Ltd.',
    'QLYS': 'Qualys Inc.',
    'TENB': 'Tenable Holdings Inc.',
    'RPD': 'Rapid7 Inc.',
    'SAIL': 'SailPoint Technologies Holdings Inc.',
    'VRNS': 'Varonis Systems Inc.',
    'FEYE': 'FireEye Inc.',
    'PFPT': 'Proofpoint Inc.',
    'SYMC': 'NortonLifeLock Inc.',
    'GEN': 'Gen Digital Inc.',
    'NLOK': 'NortonLifeLock Inc.',
    'AVGO': 'Broadcom Inc.',
    'MRVL': 'Marvell Technology Inc.',
    'QRVO': 'Qorvo Inc.',
    'SWKS': 'Skyworks Solutions Inc.',
    
    # International/ADRs
    'ASML': 'ASML Holding N.V.',
    'TSM': 'Taiwan Semiconductor Manufacturing Company Limited',
    'NVO': 'Novo Nordisk A/S',
    'RHHBY': 'Roche Holding AG',
    'NVS': 'Novartis AG',
    'SAP': 'SAP SE',
    'TM': 'Toyota Motor Corporation',
    'SNY': 'Sanofi',
    'GSK': 'GSK plc',
    'AZN': 'AstraZeneca PLC',
    'ING': 'ING Groep N.V.',
    'UBS': 'UBS Group AG',
    'CS': 'Credit Suisse Group AG',
    'DB': 'Deutsche Bank AG',
    'BBVA': 'Banco Bilbao Vizcaya Argentaria S.A.',
    'SAN': 'Banco Santander S.A.',
    'BCS': 'Barclays PLC',
    'RY': 'Royal Bank of Canada',
    'TD': 'The Toronto-Dominion Bank',
    'BMO': 'Bank of Montreal',
    'BNS': 'The Bank of Nova Scotia',
    'CM': 'Canadian Imperial Bank of Commerce',
    'SLF': 'Sun Life Financial Inc.',
    'MFC': 'Manulife Financial Corporation',
    'CNQ': 'Canadian Natural Resources Limited',
    'SU': 'Suncor Energy Inc.',
    'IMO': 'Imperial Oil Limited',
    'CNI': 'Canadian National Railway Company',
    'CP': 'Canadian Pacific Railway Limited',
    'SHOP': 'Shopify Inc.',
    'BBD': 'Bombardier Inc.',
    'AC': 'Air Canada',
    'BCE': 'BCE Inc.',
    'T': 'TELUS Corporation',
    'RCI': 'Rogers Communications Inc.',
    'QSR': 'Restaurant Brands International Inc.',
    'L': 'Loblaw Companies Limited',
    'MG': 'Magna International Inc.',
    'ATD': 'Alimentation Couche-Tard Inc.',
    'WCN': 'Waste Connections Inc.',
    'TRP': 'TC Energy Corporation',
    'ENB': 'Enbridge Inc.',
    'PPL': 'Pembina Pipeline Corporation',
    'KEY': 'KeyCorp',
    'FTS': 'Fortis Inc.',
    'EMA': 'Emera Incorporated',
    'H': 'Hydro One Limited',
    'AQN': 'Algonquin Power & Utilities Corp.',
    'BIP': 'Brookfield Infrastructure Partners L.P.',
    'BAM': 'Brookfield Asset Management Inc.',
    'BPY': 'Brookfield Property Partners L.P.',
    'BEP': 'Brookfield Renewable Partners L.P.',
    'CCO': 'Cameco Corporation',
    'FCX': 'Freeport-McMoRan Inc.',
    'GOLD': 'Barrick Gold Corporation',
    'ABX': 'Barrick Gold Corporation',
    'NEM': 'Newmont Corporation',
    'AEM': 'Agnico Eagle Mines Limited',
    'KGC': 'Kinross Gold Corporation',
    'AU': 'AngloGold Ashanti Limited',
    'PAAS': 'Pan American Silver Corp.',
    'WPM': 'Wheaton Precious Metals Corp.',
    'FNV': 'Franco-Nevada Corporation',
    'SSL': 'Sandstorm Gold Ltd.',
    'EGO': 'Eldorado Gold Corporation',
    'NGD': 'New Gold Inc.',
    'SSRM': 'SSR Mining Inc.',
    'IAMG': 'IAMGOLD Corporation',
    'CDE': 'Coeur Mining Inc.',
    'HL': 'Hecla Mining Company',
    'AG': 'First Majestic Silver Corp.',
    'SBSW': 'Sibanye Stillwater Limited',
    'PLG': 'Platinum Group Metals Ltd.',
    'SVM': 'Silvercorp Metals Inc.',
    'MUX': 'McEwen Mining Inc.',
    'GORO': 'Gold Resource Corporation',
    'MARA': 'Marathon Digital Holdings Inc.',
    'RIOT': 'Riot Blockchain Inc.',
    'COIN': 'Coinbase Global Inc.',
    'SQ': 'Block Inc.',
    'PYPL': 'PayPal Holdings Inc.',
    'V': 'Visa Inc.',
    'MA': 'Mastercard Incorporated',
    'AXP': 'American Express Company',
    'DFS': 'Discover Financial Services',
    'SYF': 'Synchrony Financial',
    'COF': 'Capital One Financial Corporation',
    'WU': 'The Western Union Company',
    'AFRM': 'Affirm Holdings Inc.',
    'LC': 'LendingClub Corporation',
    'UPST': 'Upstart Holdings Inc.',
    'SOFI': 'SoFi Technologies Inc.',
    'HOOD': 'Robinhood Markets Inc.',
    'RDFN': 'Redfin Corporation',
    'Z': 'Zillow Group Inc. Class A',
    'ZG': 'Zillow Group Inc. Class C',
    'OPEN': 'Opendoor Technologies Inc.',
    'OFFERPAD': 'OfferPad Solutions Inc.',
    'COMP': 'Compass Inc.',
    'EXPI': 'eXp World Holdings Inc.',
    'REAL': 'The RealReal Inc.',
    'RH': 'RH',
    'WSM': 'Williams-Sonoma Inc.',
    'BBY': 'Best Buy Co. Inc.',
    'TGT': 'Target Corporation',
    'WMT': 'Walmart Inc.',
    'COST': 'Costco Wholesale Corporation',
    'BJ': 'BJ\'s Wholesale Club Holdings Inc.',
    'DLTR': 'Dollar Tree Inc.',
    'DG': 'Dollar General Corporation',
    'FDO': 'Family Dollar Stores Inc.',
    'FIVE': 'Five Below Inc.',
    'OLLI': 'Ollie\'s Bargain Outlet Holdings Inc.',
    'BIG': 'Big Lots Inc.',
    'KSS': 'Kohl\'s Corporation',
    'M': 'Macy\'s Inc.',
    'JWN': 'Nordstrom Inc.',
    'GPS': 'The Gap Inc.',
    'ANF': 'Abercrombie & Fitch Co.',
    'AEO': 'American Eagle Outfitters Inc.',
    'URBN': 'Urban Outfitters Inc.',
    'LEVI': 'Levi Strauss & Co.',
    'VFC': 'V.F. Corporation',
    'PVH': 'PVH Corp.',
    'RL': 'Ralph Lauren Corporation',
    'CPRI': 'Capri Holdings Limited',
    'TPG': 'TPG Inc.',
    'KKR': 'KKR & Co. Inc.',
    'BX': 'Blackstone Inc.',
    'APO': 'Apollo Global Management Inc.',
    'CG': 'The Carlyle Group Inc.',
    'OWL': 'Blue Owl Capital Inc.',
    'ARES': 'Ares Management Corporation',
    'BAM': 'Brookfield Asset Management Inc.',
    'AMG': 'Affiliated Managers Group Inc.',
    'TROW': 'T. Rowe Price Group Inc.',
    'BEN': 'Franklin Resources Inc.',
    'IVZ': 'Invesco Ltd.',
    'NTRS': 'Northern Trust Corporation',
    'STT': 'State Street Corporation',
    'BK': 'The Bank of New York Mellon Corporation',
    'NDAQ': 'Nasdaq Inc.',
    'ICE': 'Intercontinental Exchange Inc.',
    'CME': 'CME Group Inc.',
    'CBOE': 'Cboe Global Markets Inc.',
    'MKTX': 'MarketAxess Holdings Inc.',
    'TW': 'Tradeweb Markets Inc.',
    'VIRT': 'Virtu Financial Inc.',
    'IBKR': 'Interactive Brokers Group Inc.',
    'ETFC': 'E*TRADE Financial Corporation',
    'AMTD': 'TD Ameritrade Holding Corporation',
    'SCHW': 'The Charles Schwab Corporation',
    'RJF': 'Raymond James Financial Inc.',
    'SF': 'Stifel Financial Corp.',
    'JEF': 'Jefferies Financial Group Inc.',
    'EVR': 'Evercore Inc.',
    'PJT': 'PJT Partners Inc.',
    'LAZ': 'Lazard Ltd.',
    'MC': 'Moelis & Company',
    'HLI': 'Houlihan Lokey Inc.',
    'PIPR': 'Piper Sandler Companies',
    'WMS': 'Advanced Drainage Systems Inc.',
    'MLM': 'Martin Marietta Materials Inc.',
    'VMC': 'Vulcan Materials Company',
    'CRH': 'CRH plc',
    'HWKN': 'Hawkins Inc.',
    'RPM': 'RPM International Inc.',
    'TREX': 'Trex Company Inc.',
    'AZEK': 'The AZEK Company Inc.',
    'BECN': 'Beacon Roofing Supply Inc.',
    'BLDR': 'Builders FirstSource Inc.',
    'HD': 'The Home Depot Inc.',
    'LOW': 'Lowe\'s Companies Inc.',
    'SHW': 'The Sherwin-Williams Company',
    'PPG': 'PPG Industries Inc.',
    'RPM': 'RPM International Inc.',
    'FUL': 'H.B. Fuller Company',
    'APD': 'Air Products and Chemicals Inc.',
    'LIN': 'Linde plc',
    'ECL': 'Ecolab Inc.',
    'EMN': 'Eastman Chemical Company',
    'LYB': 'LyondellBasell Industries N.V.',
    'DOW': 'Dow Inc.',
    'DD': 'DuPont de Nemours Inc.',
    'CC': 'The Chemours Company',
    'FMC': 'FMC Corporation',
    'ALB': 'Albemarle Corporation',
    'SQM': 'Sociedad Química y Minera de Chile S.A.',
    'IFF': 'International Flavors & Fragrances Inc.',
    'NTR': 'Nutrien Ltd.',
    'CF': 'CF Industries Holdings Inc.',
    'MOS': 'The Mosaic Company',
    'CTVA': 'Corteva Inc.',
    'ADM': 'Archer-Daniels-Midland Company',
    'BG': 'Bunge Limited',
    'DAR': 'Darling Ingredients Inc.',
    'TSN': 'Tyson Foods Inc.',
    'HRL': 'Hormel Foods Corporation',
    'CAG': 'Conagra Brands Inc.',
    'CPB': 'Campbell Soup Company',
    'GIS': 'General Mills Inc.',
    'K': 'Kellogg Company',
    'KHC': 'The Kraft Heinz Company',
    'MDLZ': 'Mondelez International Inc.',
    'HSY': 'The Hershey Company',
    'SJM': 'The J. M. Smucker Company',
    'MKC': 'McCormick & Company Incorporated',
    'LW': 'Lamb Weston Holdings Inc.',
    'POST': 'Post Holdings Inc.',
    'CALM': 'Cal-Maine Foods Inc.',
    'SAFM': 'Sanderson Farms Inc.',
    'PPC': 'Pilgrim\'s Pride Corporation',
    'JJSF': 'J&J Snack Foods Corp.',
    'LANC': 'Lancaster Colony Corporation',
    'SENEA': 'Seneca Foods Corporation',
    'THS': 'TreeHouse Foods Inc.',
    'INGR': 'Ingredion Incorporated',
    'CVGW': 'Calavo Growers Inc.',
    'FDP': 'Fresh Del Monte Produce Inc.',
    'DEL': 'Del Monte Foods Inc.',
    'CHEF': 'The Chefs\' Warehouse Inc.',
    'PFGC': 'Performance Food Group Company',
    'SYY': 'Sysco Corporation',
    'USFD': 'US Foods Holding Corp.',
    'UNFI': 'United Natural Foods Inc.',
    'KR': 'The Kroger Co.',
    'SFM': 'Sprouts Farmers Market Inc.',
    'GO': 'Grocery Outlet Holding Corp.',
    'INGLES': 'Ingles Markets Incorporated',
    'VLGEA': 'Village Super Market Inc.',
    'ACI': 'Albertsons Companies Inc.',
    'WBA': 'Walgreens Boots Alliance Inc.',
    'CVS': 'CVS Health Corporation',
    'RAD': 'Rite Aid Corporation',
    'FRED': 'Fred\'s Inc.',
    'HDS': 'HD Supply Holdings Inc.',
    'MSM': 'MSC Industrial Direct Co. Inc.',
    'DKS': 'DICK\'S Sporting Goods Inc.',
    'HIBB': 'Hibbett Sports Inc.',
    'BGFV': 'Big 5 Sporting Goods Corporation',
    'MODG': 'Modell\'s Sporting Goods Inc.',
    'ASO': 'Academy Sports and Outdoors Inc.',
    'PLAY': 'Dave & Buster\'s Entertainment Inc.',
    'CEC': 'California Resources Corporation',
    'TXRH': 'Texas Roadhouse Inc.',
    'DRI': 'Darden Restaurants Inc.',
    'YUM': 'Yum! Brands Inc.',
    'QSR': 'Restaurant Brands International Inc.',
    'MCD': 'McDonald\'s Corporation',
    'SBUX': 'Starbucks Corporation',
    'DNKN': 'Dunkin\' Brands Group Inc.',
    'DPZ': 'Domino\'s Pizza Inc.',
    'PZZA': 'Papa John\'s International Inc.',
    'WING': 'Wingstop Inc.',
    'BLMN': 'Bloomin\' Brands Inc.',
    'DIN': 'Dine Brands Global Inc.',
    'EAT': 'Brinker International Inc.',
    'CAKE': 'The Cheesecake Factory Incorporated',
    'RRGB': 'Red Robin Gourmet Burgers Inc.',
    'FRGI': 'Fiesta Restaurant Group Inc.',
    'JACK': 'Jack in the Box Inc.',
    'SONC': 'Sonic Corp.',
    'LOCO': 'El Pollo Loco Holdings Inc.',
    'BOBE': 'Bob Evans Farms Inc.',
    'CBRL': 'Cracker Barrel Old Country Store Inc.',
    'TACO': 'Del Taco Restaurants Inc.',
    'PEET': 'Peet\'s Coffee & Tea Inc.',
    'JAB': 'JAB Holding Company',
    'BROS': 'Dutch Bros Inc.',
    'COKE': 'Coca-Cola Consolidated Inc.',
    'KOF': 'Coca-Cola FEMSA S.A.B. de C.V.',
    'KO': 'The Coca-Cola Company',
    'PEP': 'PepsiCo Inc.',
    'MNST': 'Monster Beverage Corporation',
    'CELH': 'Celsius Holdings Inc.',
    'KDP': 'Keurig Dr Pepper Inc.',
    'COTT': 'Cott Corporation',
    'FIZZ': 'National Beverage Corp.',
    'REED': 'Reed\'s Inc.',
    'ZVIA': 'Zevia PBC',
    'STZ': 'Constellation Brands Inc.',
    'SAM': 'The Boston Beer Company Inc.',
    'TAP': 'Molson Coors Beverage Company',
    'BUD': 'Anheuser-Busch InBev SA/NV',
    'BREW': 'Craft Brew Alliance Inc.',
    'GGAL': 'Grupo Financiero Galicia S.A.',
    'PAM': 'Pampa Energía S.A.',
    'YPF': 'YPF Sociedad Anónima',
    'TEO': 'Telecom Argentina S.A.',
    'ARCO': 'Arcos Dorados Holdings Inc.',
    'LOMA': 'Loma Negra Compañía Industrial Argentina Sociedad Anónima',
    'BMA': 'Banco Macro S.A.',
    'SUPV': 'Grupo Supervielle S.A.',
    'BBAR': 'Banco BBVA Argentina S.A.',
    'CRESY': 'Cresud Sociedad Anónima Comercial Inmobiliaria Financiera y Agropecuaria',
    'IRS': 'IRSA Inversiones y Representaciones Sociedad Anónima',
    'EDN': 'Empresa Distribuidora y Comercializadora Norte Sociedad Anónima',
    'TGS': 'Transportadora de Gas del Sur S.A.',
    'TX': 'Ternium S.A.',
    'TS': 'Tenaris S.A.',
    'SID': 'Companhia Siderúrgica Nacional',
    'VALE': 'Vale S.A.',
    'PBR': 'Petróleo Brasileiro S.A. - Petrobras',
    'ITUB': 'Itaú Unibanco Holding S.A.',
    'BBD': 'Banco Bradesco S.A.',
    'ABEV': 'Ambev S.A.',
    'TIMB': 'TIM S.A.',
    'CIG': 'Companhia Energética de Minas Gerais - CEMIG',
    'EBR': 'Centrais Elétricas Brasileiras S.A. - Eletrobrás',
    'SBS': 'Companhia de Saneamento Básico do Estado de São Paulo - SABESP',
    'GGB': 'Gerdau S.A.',
    'UGP': 'Ultrapar Participações S.A.',
    'CBD': 'Companhia Brasileira de Distribuição',
    'PCAR': 'PACCAR Inc',
    'VOLV': 'Volvo AB',
    'VLVLY': 'Volvo AB',
    'SCCO': 'Southern Copper Corporation',
    'CX': 'CEMEX S.A.B. de C.V.',
    'FMX': 'Fomento Económico Mexicano S.A.B. de C.V.',
    'TV': 'Grupo Televisa S.A.B.',
    'AMX': 'América Móvil S.A.B. de C.V.',
    'TMO': 'Teléfonos de México S.A.B. de C.V.',
    'TLK': 'PT Telkom Indonesia (Persero) Tbk',
    'CHT': 'Chunghwa Telecom Co. Ltd.',
    'CHA': 'China Telecom Corporation Limited',
    'SNP': 'China Petroleum & Chemical Corporation',
    'CEO': 'CNOOC Limited',
    'PTR': 'PetroChina Company Limited',
    'LFC': 'China Life Insurance Company Limited',
    'PICC': 'The People\'s Insurance Company (Group) of China Limited',
    'ZNH': 'China Southern Airlines Company Limited',
    'CEA': 'China Eastern Airlines Corporation Limited',
    'ACH': 'Aluminum Corporation of China Limited',
    'SHI': 'Sinopec Shanghai Petrochemical Company Limited',
    'YZC': 'Yanzhou Coal Mining Company Limited',
    'HMC': 'Honda Motor Co. Ltd.',
    'TM': 'Toyota Motor Corporation',
    'NSANY': 'Nissan Motor Co. Ltd.',
    'FUJHY': 'Fuji Heavy Industries Ltd.',
    'MFG': 'Mizuho Financial Group Inc.',
    'SMFG': 'Sumitomo Mitsui Financial Group Inc.',
    'MTU': 'Mitsubishi UFJ Financial Group Inc.',
    'NMR': 'Nomura Holdings Inc.',
    'SONY': 'Sony Group Corporation',
    'CAJ': 'Canon Inc.',
    'KYOCY': 'Kyocera Corporation',
    'TKC': 'Turkcell Iletisim Hizmetleri A.S.',
    'PHI': 'PLDT Inc.',
    'IBN': 'ICICI Bank Limited',
    'HDB': 'HDFC Bank Limited',
    'TTM': 'Tata Motors Limited',
    'RDY': 'Dr. Reddy\'s Laboratories Limited',
    'WIT': 'Wipro Limited',
    'INFY': 'Infosys Limited',
    'ORCL': 'Oracle Corporation',
    'TCS': 'Tata Consultancy Services Limited',
    'VEDL': 'Vedanta Limited',
    'WNS': 'WNS (Holdings) Limited',
    'REDU': 'RISE Education Cayman Ltd',
    'GSH': 'Guangshen Railway Company Limited',
    'LPL': 'LG Display Co. Ltd.',
    'SSL': 'Sasol Limited',
    'GOLD': 'Harmony Gold Mining Company Limited',
    'AU': 'AngloGold Ashanti Limited',
    'SBSW': 'Sibanye Stillwater Limited',
    'DRD': 'DRDGOLD Limited',
    'HMY': 'Harmony Gold Mining Company Limited',
    'GFI': 'Gold Fields Limited',
    'IBA': 'Industrias Bachoco S.A.B. de C.V.',
    'KOF': 'Coca-Cola FEMSA S.A.B. de C.V.',
    'OMAB': 'Grupo Aeroportuario del Centro Norte S.A.B. de C.V.',
    'ASUR': 'Grupo Aeroportuario del Sureste S.A.B. de C.V.',
    'GAP': 'Grupo Aeroportuario del Pacífico S.A.B. de C.V.',
    'GFNORTE': 'Grupo Financiero Banorte S.A.B. de C.V.',
    'GMEXICO': 'Grupo México S.A.B. de C.V.',
    'KIMBER': 'Kimberly-Clark de México S.A.B. de C.V.',
    'LIVEPOLUS': 'Coca-Cola Bottling Co. Consolidated',
    'WALMEX': 'Wal-Mart de México S.A.B. de C.V.',
    'TLEVISA': 'Grupo Televisa S.A.B.',
    'ELEKTRA': 'Grupo Elektra S.A.B. de C.V.',
    'ALFA': 'Alfa S.A.B. de C.V.',
    'FEMSA': 'Fomento Económico Mexicano S.A.B. de C.V.',
    'BIMBO': 'Grupo Bimbo S.A.B. de C.V.',
    'KC': 'Kingsoft Cloud Holdings Limited',
    'HUYA': 'HUYA Inc.',
    'DOYU': 'DouYu International Holdings Limited',
    'YY': 'JOYY Inc.',
    'MOMO': 'Momo Inc.',
    'IQ': 'iQIYI Inc.',
    'BZUN': 'Baozun Inc.',
    'VIPS': 'Vipshop Holdings Limited',
    'WB': 'Weibo Corporation',
    'SINA': 'Sina Corporation',
    'SOHU': 'Sohu.com Limited',
    'NTES': 'NetEase Inc.',
    'BIDU': 'Baidu Inc.',
    'BABA': 'Alibaba Group Holding Limited',
    'JD': 'JD.com Inc.',
    'PDD': 'PDD Holdings Inc.',
    'TCOM': 'Trip.com Group Limited',
    'DIDI': 'Didi Global Inc.',
    'LI': 'Li Auto Inc.',
    'NIO': 'NIO Inc.',
    'XPEV': 'XPeng Inc.',
    'NIU': 'Niu Technologies',
    'TAL': 'TAL Education Group',
    'EDU': 'New Oriental Education & Technology Group Inc.',
    'GOTU': 'Gaotu Techedu Inc.',
    'COE': 'China Online Education Group',
    'DL': 'China Distance Education Holdings Limited',
    'TEDU': 'Tarena International Inc.',
    'LAIX': 'LAIX Inc.',
    'REDU': 'RISE Education Cayman Ltd',
    'YQ': 'YOUDAO Inc.',
    'ZYME': 'Zymeworks Inc.',
    'ZIOP': 'ZIOPHARM Oncology Inc.',
    'FOLD': 'Amicus Therapeutics Inc.',
    'RARE': 'Ultragenyx Pharmaceutical Inc.',
    'BLUE': 'bluebird bio Inc.',
    'EDIT': 'Editas Medicine Inc.',
    'NTLA': 'Intellia Therapeutics Inc.',
    'CRSP': 'CRISPR Therapeutics AG',
    'BEAM': 'Beam Therapeutics Inc.',
    'PRIME': 'Prime Medicine Inc.',
    'VERV': 'Verve Therapeutics Inc.',
    'ARCT': 'Arcturus Therapeutics Holdings Inc.',
    'MRNA': 'Moderna Inc.',
    'BNTX': 'BioNTech SE',
    'NVAX': 'Novavax Inc.',
    'INO': 'Inovio Pharmaceuticals Inc.',
    'OCGN': 'Ocugen Inc.',
    'VXRT': 'Vaxart Inc.',
    'ALTY': 'Global X Alternet Fund',
    'ARKK': 'ARK Innovation ETF',
    'ARKQ': 'ARK Autonomous Technology & Robotics ETF',
    'ARKW': 'ARK Next Generation Internet ETF',
    'ARKG': 'ARK Genomic Revolution ETF',
    'ARKF': 'ARK Fintech Innovation ETF',
    'PRNT': 'The 3D Printing ETF',
    'IZRL': 'ARK Israel Innovative Technology ETF',
}

def get_company_name(ticker: str) -> str:
    """
    Get the full company name for a ticker symbol.
    
    Args:
        ticker: Stock ticker symbol
        
    Returns:
        Full company name or the ticker if not found
    """
    return COMPANY_NAMES.get(ticker.upper(), ticker)

def update_company_name(ticker: str, company_name: str):
    """
    Add or update a company name mapping.
    
    Args:
        ticker: Stock ticker symbol
        company_name: Full company name
    """
    COMPANY_NAMES[ticker.upper()] = company_name

def get_all_tickers() -> list:
    """Get list of all available ticker symbols."""
    return list(COMPANY_NAMES.keys())

def search_companies(search_term: str) -> dict:
    """
    Search for companies by ticker or name.
    
    Args:
        search_term: Search term to match against ticker or company name
        
    Returns:
        Dictionary of matching ticker: company_name pairs
    """
    search_term = search_term.upper()
    matches = {}
    
    for ticker, name in COMPANY_NAMES.items():
        if search_term in ticker or search_term.upper() in name.upper():
            matches[ticker] = name
            
    return matches