[browser]
gatherUsageStats = false

[global]
disableWatchdogWarning = true

[server]
headless = true
enableXsrfProtection = false
enableWebsocketCompression = false
address = "0.0.0.0"
port = 3000
maxUploadSize = 50
maxMessageSize = 200
enableStaticServing = false
runOnSave = false
allowRunOnSave = false

[theme]
base = "light"
